spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: postService

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pages}
    username: ${DB_USERNAME:kabi}
    password: ${DB_PASSWORD:kabil@007}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          json_format_mapper: com.bamboo.postService.common.hibernate.CustomHibernateJsonFormatter

  data:
    web:
      pageable:
        max-page-size: 10
        default-page-size: 10

server:
  port: ${SERVER_PORT:8090}
user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8091}
s3:
  bucket:
    name: spring-uploads
    baseUrl: http://localhost:8443
